@extends('layouts.app')

@section('content')
    <div class="container">
        <h1 style="text-align: center">O firmie</h1>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce dolor urna, vulputate id mattis et, rhoncus ut risus. Fusce in euismod velit, et pulvinar dolor. Aliquam suscipit metus nec ultrices faucibus. Aenean vitae mi in neque lacinia laoreet. Phasellus accumsan sagittis nulla, at sodales est ornare et. Aenean luctus enim nec mi euismod, quis fermentum mi sollicitudin. Etiam rhoncus magna eget lacus vehicula, nec lobortis est eleifend. Suspendisse eu risus tortor. Mauris scelerisque pharetra hendrerit. Curabitur ex lacus, aliquet in tellus et, pulvinar volutpat felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam efficitur est in quam facilisis commodo. </p>
        <p> Donec non mauris ut magna eleifend faucibus at eget leo. Pellentesque nec risus augue. Phasellus ultrices est augue, quis fringilla leo iaculis quis. Fusce ex turpis, consectetur blandit sodales sed, dignissim in tortor. Suspendisse facilisis elit tortor, sed mattis libero tempus vitae. Etiam id leo eu nisi tempor maximus. Donec ac leo eu justo scelerisque ultrices. Fusce posuere condimentum luctus. Nunc luctus dui eget justo euismod, vitae mattis orci laoreet. Aenean blandit libero a tincidunt pretium. </p>
        <p> Suspendisse interdum, nisi in molestie mollis, nibh mauris scelerisque tellus, at aliquam est libero sit amet est. Etiam sit amet bibendum nunc, in luctus velit. Pellentesque in mi nibh. Duis quis consectetur sapien. Phasellus fermentum lacus sed sapien gravida condimentum. Aliquam erat volutpat. Aenean feugiat arcu quis erat egestas maximus. Donec ac varius risus, et rutrum sem. Duis justo tellus, hendrerit at quam eget, accumsan vulputate odio. Suspendisse nec velit auctor, placerat purus vitae, feugiat arcu. Maecenas scelerisque maximus ante ullamcorper aliquet. </p>
    </div>
@endsection
